### ISSUE TITLE
Question from a noob to your plugin...

### ISSUE THREAD

**Issue by jajourda** [avillafiorita/jekyll-datapage_gen#14]
What is the difference between this plugin and jekyll collections:

https://jekyllrb.com/docs/collections/

Someone who works at [cloudcannon ](http://cloudcannon.com/)was corresponding with me and said the following about your plugin:

>  I think I've seen that plugin before but have never had a use case for it not handled already by Jekyll collections. 

But i feel like the strength of yours is primarily found in building nearly everything with json, as well as being able to do more complicated includes.

**Comment by avillafiorita** [comment]
Thanks for your question. When I first released the plugin, collections were not yet implemented, I believe. 

I have never had the need to use collections. By reading the Jekyll docs it seems that you can use my plugin and collections to do the same things: represent complex data with yaml and render it by either generating one file per record or by creating a single page with all records. So, at the end it probably boils down to how you prefer to represent your data. 

If you prefer to list all your records in a single yaml (or json) file, use this plugin. This might be useful if your yaml file is generated by some other piece of code or if you want to quickly check that all record have the same fields, for instance. Another advantage is that the plugin requires you to store the files in the _data directory, the standard location for this kind of information. (BTW, one question you might ask is, in fact, why do you need Jekyll's _data directory, if you have collections?)

However, if you have complex records, collections might be a better choice, since you have to use one file per record. Another advantage is that collections ship with Jekyll and, by using collections, you can remove one dependency from your code, namely that from my plugin ... but why doing it, when my plugin works so well? :-)
