### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by geloangelia** [avillafiorita/jekyll-datapage_gen#22]
Hi i used your plugin but its giving me this error:

D:\Gelo Files\Github\vcsites>jekyll build
WARN: Unresolved specs during Gem::Specification.reset:
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: D:/Gelo Files/Github/vcsites/_config.yml
            Source: D:/Gelo Files/Github/vcsites
       Destination: D:/Gelo Files/Github/vcsites/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.4.0 | Error:  undefined method `downcase' for nil:NilClass

**Comment by geloangelia** [comment]
jekyll 3.4.0 | Error:  undefined method `downcase' for nil:NilClass

**Comment by avillafiorita** [comment]
Hi
difficult to understand what the error is without sources.

main main guess is that the field "name" in the yaml specification has some issues. Could you please check the following:

- did you specify what field is used to generate the filenames? (look at the doc of field "name" in the yaml specification of the `page_gen` directive)
- does the field `name` reference a field which is non-nil for each record you would like to generate pages for? (e.g. all the records in your _data have a non-nil content for the field specified in `name`)

Otherwise, if you can send me the data you are using to generate the pages, I can try and have a look.

**Comment by geloangelia** [comment]
Heres my repository: https://github.com/geloangelia/vcsites

**Comment by geloangelia** [comment]
Hi @avillafiorita Im not getting the error once I change the data from "name" field.

**Comment by geloangelia** [comment]
Unfortunately, The links is showing in the header on my html and not on a specific page/layout.

**Comment by avillafiorita** [comment]
Hi-
Links showing in the header seems to be a feature of the "minima" template and is not related to this plugin.

You also need to use `datapage_url` for links to work properly.

For instance:

<pre>
{% for item in site.data.vclist %}
   <p><a class="page-link" href="{{ item.Name | datapage_url: 'vclistcontent' }}"> {{ item.Name }}</a></p>
 {% endfor %}
</pre>

will generate a link to the page built from the record in `vclist` identified by `Name`. The link expects the page to be in the directory `vclistcontent`.

**Comment by geloangelia** [comment]
I havent put a code to list the names. but its automatically showing on my header.
Is followed all steps

**Comment by avillafiorita** [comment]
Links showing in the header seems to be a feature of the "minima" template (your site is using) and is not related to this plugin.
