### ISSUE TITLE
Is it possible to just run a command to generate those files and then let the Jekyll run on it's own?

### ISSUE THREAD

**Issue by faizanvahevaria** [avillafiorita/jekyll-datapage_gen#38]
Like, first create the html files from data files and then run the Jekyll Serve.

I want to create HTML files for each record in data files but still, want to be able to edit content using CloudCannon CMS.

Is there any workaround for this?

**Comment by avillafiorita** [comment]
The plugin generates html pages on build and serve. 

However, if you need to launch the generator on an external service (such as Github Pages or, possibly, CloudCannon), there is the issue that only certain plugins can be run. You should consult their documentation for possible workarounds.

If you come out with a recipe to make it work, please share it, so that I can link it in the documentation of this plugin.
