### ISSUE TITLE
Generating index.html files

### ISSUE THREAD

**Issue by JKillian** [avillafiorita/jekyll-datapage_gen#8]
When I use this script, I end up with a directory layout like this:

```
pets
- dog.html
- cat.html
```

Is there a way to generate this instead?

```
pets
- dog
  - index.html
- cat
  - index.html
```

Thanks!

**Comment by avillafiorita** [comment]
I have just pushed a version which adds support for your feature. Add in the _config.yml the following directive:

page_gen-dirs: true

and the pages will be generated in named folders. 
Have a try and let me know (... there is something magic going on, since I wrote less code that I thought necessary)

**Comment by avillafiorita** [comment]
closed
