### ISSUE TITLE
How to make it works with `Jekyll-feed` plugin or is there a better way to generate a `atom/rss` feed?

### ISSUE THREAD

**Issue by JakiChen** [avillafiorita/jekyll-datapage_gen#92]
1. It's useful, when i generate a `project` page?
2. I'm interested that is there a way make it works with `Jekyll-feed` plugin.

**Comment by avillafiorita** [comment]
Hi Jaki,
1. yes, it can be used to generate a list of projects you or your organization worked on, with the possibility of having one page per project. (This is how we used it on our website, for instance.)
2. maybe, but in this scenario, using Jekyll _posts seem to be more appropriate.

Let me know if it answers your question, so that I can close the issue. (and sorry for taking so long to get back to you.)

**Comment by JakiChen** [comment]
thanks，
